{% set name = "ndvi2gif" %}
{% set version = "0.0.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: python -m pip install .

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy <2.0
    - matplotlib
    - pillow
    - imageio
    - tqdm
    - geemap ==0.29.5
    - earthengine-api >=0.1.347
    - pip
    - pip:
        - deims>=4.0

about:
  home: https://github.com/Digdgeo/Ndvi2Gif
  license: MIT
  license_file: LICENSE
  summary: Generate seasonal composites and extract statistical summaries from any remote sensing index using Google Earth Engine and geemap
  description: |
    NDVI2GIF allows researchers to generate seasonal composites and extract summaries from any GEE-compatible index. Output includes animations and statistical summaries useful for vegetation monitoring.
  author: Diego García Díaz
  author_email: diegogarcia@ebd.csic.es

extra:
  recipe-maintainers:
    - Digdgeo
