package:
  name: ndvi2gif
  version: "0.0.9"

source:
  path: ..

build:
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - geemap ==0.29.5
    - earthengine-api >=0.1.347
    - numpy <2.0
    - matplotlib
    - pillow
    - imageio
    - tqdm
    - deims >=4.0

about:
  home: https://github.com/Digdgeo/Ndvi2Gif
  license: MIT
  license_family: MIT
  summary: Generate seasonal composites and extract statistical summaries from several remote sensing index using Google Earth Engine and geemap
  description: |
    Tools to generate seasonal composites, extract index statistics and create seasonal gifs with Google Earth Engine.
  author: Diego García Díaz
  maintainer: Diego García Díaz
  maintainer_email: diegogarcia@ebd.csic.es

extra:
  recipe-maintainers:
    - Digdgeo
